export const statsData = [
  {
    title: "Total Users",
    icon: "users",
    value: "0",
    decision: "increment",
    percentage: "+16.2%",
    iconBg: "bg-totalUserBg",
    iconFg: "text-totalUserFg",
  },
  {
    title: "Super Admins",
    icon: "admins",
    value: "0",
    decision: "decrement",
    percentage: "-08.08%",
    iconBg: "bg-premiumUserBg",
    iconFg: "text-premiumUserFg",
  },
  {
    title: "Organizations",
    icon: "oraganizations",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
  {
    title: "Organizational Users",
    icon: "users",
    value: "0",
    decision: "decrement",
    percentage: "-08.08%",
    iconBg: "bg-premiumUserBg",
    iconFg: "text-premiumUserFg",
  },
  {
    title: "Public Users",
    icon: "users",
    value: "0",
    decision: "decrement",
    percentage: "-08.08%",
    iconBg: "bg-premiumUserBg",
    iconFg: "text-premiumUserFg",
  },
  {
    title: "Premium Users",
    icon: "premium",
    value: "0",
    decision: "decrement",
    percentage: "-08.08%",
    iconBg: "bg-premiumUserBg",
    iconFg: "text-premiumUserFg",
  },
  {
    title: "Active Users",
    icon: "userCheck",
    value: "0",
    decision: "increment",
    percentage: "+12.08%",
    iconBg: "bg-activeUserBg",
    iconFg: "text-activeUserFg",
  },
  {
    title: "New Users",
    icon: "userPlus",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
  {
    title: "Services",
    icon: "services",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
  {
    title: "Premium Services",
    icon: "premiumServices",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
  {
    title: "Projects",
    icon: "projects",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
];
