import { TRole } from "./type";

export const rolesPermissions: Record<TRole, string[]> = {
  "Admin": [
    "dashboard",
    "users",
    "premium-users",
    "organizations",
    "services",
    "projects",
    "files",
    "chat-group",
    "notifications",
    "messages",
    "reports-bans",
    "manage-admins",
  ],
  "Super Admin": [
    "dashboard",
    "users",
    "organizations",
    "services",
    "projects",
    "chat-group",
    "notifications",
    "messages",
    "reports-bans",
    "manage-admins",
  ],
  "Project Manager": [
    "dashboard",
    "organizations",
    "users",
    "projects",
    "chat-group",
    "notifications",
    "messages",
  ],
  "Developer": [
    "dashboard",
    "projects",
    "files",
    "chat-group",
    "notifications",
  ],
  "Team Member": [
    "dashboard",
    "projects",
    "files",
    "chat-group",
    "notifications",
  ],
  "User": [
    "dashboard",
    "projects",
    "files",
    "chat-group",
    "notifications",
  ],
};